import json

STORES = [
    {"id": "ah", "naam": "AH", "volledig": "Albert Heijn", "factor": 1.0},
    {"id": "jumbo", "naam": "Jumbo", "volledig": "Jumbo", "factor": 0.98},
    {"id": "lidl", "naam": "Lidl", "volledig": "Lidl", "factor": 0.85},
    {"id": "hoogvliet", "naam": "Hoogvliet", "volledig": "Hoogvliet", "factor": 0.92},
]
APPLIANCES = [
    ["fornuis", "Fornuis"], ["oven", "Oven"], ["magnetron", "Magnetron"],
    ["airfryer", "Airfryer"], ["slowcooker", "Slowcooker"],
    ["snelkookpan", "Snelkookpan"], ["blender", "Blender"], ["staafmixer", "Staafmixer"],
]
ALLERGENS = [
    ["gluten", "Gluten"], ["melk", "Melk / lactose"], ["ei", "Ei"], ["pinda", "Pinda"],
    ["noten", "Noten"], ["soja", "Soja"], ["vis", "Vis"], ["schaaldieren", "Schaaldieren"],
    ["selderij", "Selderij"], ["mosterd", "Mosterd"], ["sesam", "Sesam"],
]
DEPTS = [
    ["agf", "Groente & fruit"], ["vlees", "Vlees & vis"], ["zuivel", "Zuivel, eieren & vega"],
    ["brood", "Brood"], ["droog", "Pasta, rijst & granen"], ["blik", "Blik & pot"],
    ["saus", "Sauzen & beleg"], ["diepvries", "Diepvries"], ["overig", "Overig"],
    ["kruid", "Voorraadkast"],
]


def I(id, naam, unit, pack, price, dept, fl="", al="", q=None, must=None, pantry=False):
    d = dict(id=id, naam=naam, unit=unit, pack=pack, price=price, dept=dept,
             fl=fl.split() if fl else [], al=al.split() if al else [], q=q or naam.lower())
    if must:
        d["must"] = must.split()
    if pantry:
        d["pantry"] = True
    return d


ING = [
    I("ui", "Ui", "g", 1000, 1.79, "agf", q="uien", must="uien ui"),
    I("knoflook", "Knoflook", "teen", 12, 0.99, "agf", q="knoflook", must="knoflook"),
    I("tomaat", "Tomaat", "g", 500, 2.49, "agf", q="trostomaten", must="tomaat tomaten"),
    I("cherrytomaat", "Cherrytomaat", "g", 250, 1.99, "agf", q="cherrytomaten", must="cherry"),
    I("paprika", "Paprika", "st", 3, 2.49, "agf", q="paprika rood geel groen", must="paprika"),
    I("courgette", "Courgette", "g", 400, 1.19, "agf", q="courgette", must="courgette"),
    I("wortel", "Wortel", "g", 1000, 1.59, "agf", q="wortelen", must="wortel"),
    I("champignon", "Champignons", "g", 250, 1.79, "agf", q="champignons", must="champignon"),
    I("broccoli", "Broccoli", "g", 500, 1.99, "agf", q="broccoli", must="broccoli"),
    I("bloemkool", "Bloemkool", "g", 700, 2.29, "agf", q="bloemkool", must="bloemkool"),
    I("sperzieboon", "Sperziebonen", "g", 400, 2.19, "agf", q="sperziebonen", must="sperzie"),
    I("aardappel", "Aardappelen", "g", 2000, 2.79, "agf", q="aardappelen", must="aardappel"),
    I("zoeteaardappel", "Zoete aardappel", "g", 700, 2.49, "agf", q="zoete aardappel", must="zoete"),
    I("komkommer", "Komkommer", "st", 1, 0.89, "agf", q="komkommer", must="komkommer"),
    I("slamix", "Slamix", "g", 200, 1.89, "agf", q="sla mix", must="sla"),
    I("prei", "Prei", "g", 300, 1.49, "agf", q="prei", must="prei"),
    I("pompoen", "Butternut pompoen", "g", 1000, 2.29, "agf", q="butternut pompoen", must="butternut pompoen"),
    I("citroen", "Citroen", "st", 1, 0.59, "agf", q="citroen", must="citroen"),
    I("roerbakmix", "Roerbakgroente", "g", 400, 2.39, "agf", q="roerbakgroente", must="roerbak wok"),
    I("boerenkool", "Boerenkool (gesneden)", "g", 500, 1.99, "agf", q="boerenkool gesneden", must="boerenkool"),
    I("banaan", "Banaan", "st", 5, 1.69, "agf", q="bananen", must="banaan bananen"),
    I("appel", "Appel", "st", 6, 2.69, "agf", q="appels", must="appel appels elstar"),
    I("blauwebessen", "Blauwe bessen", "g", 125, 2.49, "agf", q="blauwe bessen", must="blauwe"),
    I("avocado", "Avocado", "st", 2, 2.39, "agf", q="avocado", must="avocado"),

    I("kipfilet", "Kipfilet", "g", 500, 6.79, "vlees", "meat animal", q="kipfilet", must="kipfilet"),
    I("kippendij", "Kippendijfilet", "g", 500, 5.79, "vlees", "meat animal", q="kippendijfilet", must="kippendij"),
    I("gehakt", "Rundergehakt", "g", 500, 5.19, "vlees", "meat animal", q="rundergehakt", must="rundergehakt"),
    I("rookworst", "Rookworst", "g", 275, 2.99, "vlees", "meat animal pork", q="rookworst", must="rookworst"),
    I("stoofvlees", "Stoofvlees (rund)", "g", 500, 7.49, "vlees", "meat animal", q="rundvlees stoofvlees", must="stoof"),
    I("zalm", "Zalmfilet", "g", 250, 5.99, "vlees", "fish animal", "vis", q="zalmfilet", must="zalm"),
    I("gerooktezalm", "Gerookte zalm", "g", 100, 3.49, "vlees", "fish animal", "vis", q="gerookte zalm", must="gerookte"),

    I("ei", "Eieren", "st", 10, 3.29, "zuivel", "animal", "ei", q="eieren scharrel", must="eieren ei"),
    I("melk", "Melk", "ml", 1000, 1.29, "zuivel", "animal", "melk", q="halfvolle melk", must="melk"),
    I("haverdrink", "Haverdrink", "ml", 1000, 1.69, "zuivel", "", "gluten", q="haverdrink", must="haver"),
    I("kookroom", "Kookroom", "ml", 250, 1.39, "zuivel", "animal", "melk", q="kookroom", must="kookroom room"),
    I("kaas", "Geraspte kaas", "g", 200, 2.49, "zuivel", "animal stremsel", "melk", q="geraspte kaas", must="geraspte"),
    I("feta", "Feta", "g", 200, 2.29, "zuivel", "animal stremsel", "melk", q="feta", must="feta"),
    I("mozzarella", "Mozzarella", "g", 125, 0.99, "zuivel", "animal stremsel", "melk", q="mozzarella", must="mozzarella"),
    I("yoghurt", "Griekse yoghurt", "g", 500, 1.89, "zuivel", "animal", "melk", q="griekse yoghurt", must="yoghurt"),
    I("kwark", "Magere kwark", "g", 500, 1.49, "zuivel", "animal", "melk", q="magere kwark", must="kwark"),
    I("cottage", "Cottage cheese", "g", 200, 1.59, "zuivel", "animal", "melk", q="cottage cheese", must="cottage"),
    I("tofu", "Tofu naturel", "g", 200, 1.99, "zuivel", "", "soja", q="tofu naturel", must="tofu"),

    I("wraps", "Tortilla wraps", "st", 6, 1.79, "brood", "", "gluten", q="tortilla wraps", must="wraps tortilla"),
    I("stokbrood", "Volkoren stokbrood", "g", 250, 1.39, "brood", "", "gluten", q="volkoren stokbrood", must="stokbrood"),
    I("volkorenbrood", "Volkorenbrood", "sn", 16, 2.19, "brood", "", "gluten", q="volkorenbrood", must="volkoren"),

    I("pasta", "Penne", "g", 500, 1.39, "droog", "", "gluten", q="penne", must="penne"),
    I("volkorenpasta", "Volkorenpasta", "g", 500, 1.79, "droog", "", "gluten", q="volkoren pasta", must="volkoren"),
    I("rijst", "Rijst (basmati)", "g", 1000, 2.89, "droog", q="basmati rijst", must="basmati rijst"),
    I("zilvervliesrijst", "Zilvervliesrijst", "g", 1000, 3.19, "droog", q="zilvervliesrijst", must="zilvervlies"),
    I("mie", "Mie noedels", "g", 250, 1.29, "droog", "", "gluten ei", q="mie noedels", must="mie"),
    I("couscous", "Couscous", "g", 500, 1.69, "droog", "", "gluten", q="couscous", must="couscous"),
    I("rodelinzen", "Rode linzen (droog)", "g", 500, 2.29, "droog", q="rode linzen", must="linzen"),
    I("spliterwten", "Spliterwten (droog)", "g", 500, 1.89, "droog", q="spliterwten", must="splitt spliterwten erwten"),
    I("havermout", "Havermout", "g", 500, 1.29, "droog", "", "gluten", q="havermout", must="havermout haver"),
    I("walnoten", "Walnoten", "g", 200, 3.49, "droog", "", "noten", q="walnoten", must="walnoten"),

    I("tomatenblokjes", "Tomatenblokjes", "g", 400, 0.99, "blik", q="tomatenblokjes", must="tomaten"),
    I("tomatenpuree", "Tomatenpuree", "g", 70, 0.89, "blik", q="tomatenpuree", must="tomatenpuree"),
    I("kidneybonen", "Kidneybonen", "g", 240, 1.19, "blik", q="kidneybonen", must="kidney"),
    I("kikkererwten", "Kikkererwten", "g", 240, 1.09, "blik", q="kikkererwten", must="kikkererwten"),
    I("linzen", "Bruine linzen (blik)", "g", 240, 1.29, "blik", q="linzen blik", must="linzen"),
    I("mais", "Mais", "g", 285, 1.09, "blik", q="mais blik", must="mais"),
    I("kokosmelk", "Kokosmelk", "ml", 400, 1.39, "blik", q="kokosmelk", must="kokos"),
    I("tonijn", "Tonijn in blik", "g", 145, 1.89, "blik", "fish animal", "vis", q="tonijn in water", must="tonijn"),

    I("pindakaas", "Pindakaas", "g", 350, 2.19, "saus", "", "pinda", q="pindakaas", must="pindakaas"),
    I("ketjap", "Ketjap manis", "ml", 250, 1.69, "saus", "", "soja gluten", q="ketjap manis", must="ketjap"),
    I("sojasaus", "Sojasaus", "ml", 150, 1.89, "saus", "", "soja gluten", q="sojasaus", must="soja"),
    I("pesto", "Pesto groen", "g", 190, 1.99, "saus", "animal stremsel", "melk noten", q="pesto groen", must="pesto"),
    I("hummus", "Hummus", "g", 200, 1.79, "saus", "", "sesam", q="hummus", must="hummus"),
    I("honing", "Honing", "g", 350, 2.99, "saus", "animal", "", q="honing", must="honing"),

    I("spinazie", "Spinazie (diepvries)", "g", 450, 1.69, "diepvries", q="spinazie diepvries", must="spinazie"),
    I("garnalen", "Garnalen (diepvries)", "g", 200, 4.49, "diepvries", "fish animal", "schaaldieren", q="garnalen", must="garnalen"),

    I("olijfolie", "Olijfolie", "ml", 500, 5.49, "kruid", q="olijfolie", pantry=True),
    I("kerrie", "Kerriepoeder", "g", 40, 1.99, "kruid", q="kerriepoeder", pantry=True),
    I("komijn", "Komijn", "g", 40, 1.99, "kruid", q="komijn", pantry=True),
    I("paprikapoeder", "Paprikapoeder", "g", 40, 1.99, "kruid", q="paprikapoeder", pantry=True),
    I("italiaans", "Italiaanse kruiden", "g", 25, 1.79, "kruid", q="italiaanse kruiden", pantry=True),
    I("bouillon", "Bouillonblokjes", "st", 8, 1.49, "kruid", "", "selderij", q="bouillonblokjes", pantry=True),
    I("mosterd", "Mosterd", "g", 200, 1.59, "kruid", "", "mosterd", q="mosterd", pantry=True),
]


def R(id, naam, meals, t, w, needs, cat, ing, v, e, kcal, steps):
    return dict(
        id=id, naam=naam, meals=meals.split(), t=t, w=w,
        needs=needs.split() if needs else [], cat=cat,
        ing=[[a.split(":")[0], float(a.split(":")[1])] for a in ing.split()],
        v=v, e=e, kcal=kcal, steps=steps.split("|"),
    )


REC = [
    # ---------------- DINER ----------------
    R("bolognese", "Spaghetti bolognese met extra groente", "diner", 35, 0, "fornuis", "rund",
      "volkorenpasta:90 gehakt:100 ui:60 knoflook:1 wortel:60 tomatenblokjes:200 tomatenpuree:15 italiaans:1 olijfolie:10",
      11, 34, 640,
      "Fruit ui en knoflook, bak het gehakt rul en voeg geraspte wortel toe.|Roer tomatenpuree en blokjes erdoor en laat 20 minuten zacht pruttelen.|Kook de pasta beetgaar en meng met de saus."),
    R("kipkerrie", "Kip kerrie met rijst", "diner", 30, 0, "fornuis", "kip",
      "kipfilet:130 ui:60 paprika:0.5 kokosmelk:100 zilvervliesrijst:70 kerrie:1 olijfolie:10",
      6, 36, 650,
      "Kook de rijst volgens de verpakking.|Bak kip, ui en paprika aan en voeg de kerrie toe.|Giet de kokosmelk erbij en laat 10 minuten sudderen."),
    R("kipsate", "Kip sate met rijst en sperziebonen", "diner", 30, 0, "fornuis", "kip",
      "kippendij:130 pindakaas:25 ketjap:15 zilvervliesrijst:70 sperzieboon:150 ui:40 knoflook:1",
      7, 38, 690,
      "Bak de kip bruin met ui en knoflook.|Roer pindakaas, ketjap en een scheutje water tot een saus.|Serveer met rijst en gestoomde sperziebonen."),
    R("zalmoven", "Zalm uit de oven met aardappel en broccoli", "diner", 15, 25, "oven", "vis",
      "zalm:125 aardappel:250 broccoli:200 citroen:0.25 olijfolie:10",
      10, 32, 620,
      "Snijd de aardappel in partjes en rooster 15 minuten op 200 graden.|Leg de zalm en broccoli erbij en rooster nog 12 minuten.|Maak af met citroensap."),
    R("boerenkoolstamp", "Boerenkoolstamppot met rookworst", "diner", 35, 0, "fornuis", "varken",
      "aardappel:250 boerenkool:150 rookworst:100 melk:30 mosterd:1",
      8, 22, 560,
      "Kook de aardappelen gaar, voeg de boerenkool de laatste 5 minuten toe.|Stamp met melk en mosterd tot een stamppot.|Verwarm de rookworst mee of in een pan."),
    R("linzensoep", "Linzensoep met wortel", "lunch diner", 25, 10, "fornuis", "vega",
      "linzen:120 wortel:100 ui:60 tomatenblokjes:100 stokbrood:50 bouillon:1 kerrie:1",
      14, 17, 420,
      "Fruit ui en wortel, voeg kerrie, linzen en blokjes tomaat toe.|Giet bouillon erbij en laat 15 minuten koken.|Serveer met stokbrood."),
    R("kikkererwtencurry", "Kikkererwtencurry met rijst", "diner", 30, 0, "fornuis", "vega",
      "kikkererwten:120 kokosmelk:100 tomatenblokjes:100 spinazie:100 ui:60 knoflook:1 zilvervliesrijst:70 kerrie:1",
      12, 18, 680,
      "Kook de rijst.|Fruit ui en knoflook met kerrie, voeg kikkererwten, tomaat en kokosmelk toe.|Laat 10 minuten pruttelen en roer de spinazie erdoor."),
    R("chili", "Chili sin carne met rijst", "diner", 35, 0, "fornuis", "vega",
      "kidneybonen:120 mais:70 paprika:0.5 tomatenblokjes:200 ui:60 knoflook:1 zilvervliesrijst:65 komijn:1",
      14, 16, 560,
      "Fruit ui, knoflook en paprika met komijn.|Voeg bonen, mais en tomaat toe en laat 20 minuten koken.|Serveer met rijst."),
    R("shakshuka", "Shakshuka met brood", "ontbijt lunch diner", 25, 0, "fornuis", "ei",
      "ei:2 tomatenblokjes:200 paprika:0.5 ui:60 knoflook:1 feta:40 stokbrood:60 komijn:1",
      9, 25, 520,
      "Fruit ui, paprika en knoflook met komijn, voeg de tomaat toe en laat 10 minuten koken.|Maak kuiltjes en laat de eieren er 5 minuten in garen met deksel erop.|Strooi feta erover en serveer met brood."),
    R("pestopasta", "Pasta pesto met kip en cherrytomaat", "diner", 25, 0, "fornuis", "kip",
      "pasta:90 kipfilet:120 pesto:25 cherrytomaat:100 courgette:100",
      6, 40, 700,
      "Kook de pasta.|Bak kip, courgette en tomaatjes gaar.|Meng pasta en pesto erdoor."),
    R("kipmie", "Roerbak met kip en mie", "diner", 25, 0, "fornuis", "kip",
      "kipfilet:120 mie:80 roerbakmix:200 sojasaus:15 ui:40 knoflook:1",
      7, 38, 600,
      "Kook de mie en giet af.|Roerbak kip, ui, knoflook en groente op hoog vuur.|Voeg mie en sojasaus toe en schep om."),
    R("tofuroerbak", "Tofu-groente roerbak met rijst", "diner", 25, 0, "fornuis", "vega",
      "tofu:180 roerbakmix:200 sojasaus:15 rijst:70 ui:40 knoflook:1",
      6, 30, 560,
      "Kook de rijst.|Bak de tofublokjes krokant, voeg ui, knoflook en groente toe.|Maak af met sojasaus."),
    R("gehaktballetjes", "Gehaktballetjes in tomatensaus met pasta", "diner", 40, 0, "fornuis", "rund",
      "gehakt:120 ei:0.5 ui:40 tomatenblokjes:200 pasta:90 italiaans:1",
      7, 38, 700,
      "Meng gehakt, ei en fijngesneden ui en rol er balletjes van.|Bak ze bruin en giet de tomaat erover, laat 15 minuten garen.|Kook de pasta en serveer."),
    R("ovenpastabroc", "Ovenschotel pasta met broccoli en kaas", "diner", 15, 25, "oven", "vega",
      "pasta:90 broccoli:150 kaas:40 kookroom:50 ui:40 knoflook:1",
      8, 27, 690,
      "Kook de pasta met de broccoli de laatste 3 minuten mee.|Meng met kookroom, ui en knoflook in een ovenschaal.|Bestrooi met kaas en gratineer 20 minuten op 200 graden."),
    R("gevuldezoete", "Gevulde zoete aardappel met bonen en feta", "diner", 15, 30, "oven|airfryer", "vega",
      "zoeteaardappel:300 kidneybonen:100 feta:40 mais:50 paprika:0.33 yoghurt:40",
      15, 22, 560,
      "Prik de zoete aardappel in en bak 30 minuten in oven of airfryer.|Verwarm bonen, mais en paprika in een pan.|Snijd open, vul en top met feta en yoghurt."),
    R("airfryerkip", "Airfryer kip met zoete aardappelfrites", "diner", 30, 0, "airfryer|oven", "kip",
      "kippendij:150 zoeteaardappel:250 slamix:60 komkommer:0.3 yoghurt:50 paprikapoeder:1",
      8, 36, 600,
      "Snijd de zoete aardappel in frites en kruid kip en frites met paprikapoeder.|Gaar de kip 15 minuten en de frites 20 minuten op 190 graden.|Maak een salade met yoghurt-dressing."),
    R("airfryerzalm", "Airfryer zalm met couscous", "diner", 25, 0, "airfryer|oven", "vis",
      "zalm:125 couscous:70 courgette:100 cherrytomaat:80 citroen:0.25 olijfolie:10",
      6, 33, 590,
      "Gaar zalm en courgette 10 minuten op 180 graden.|Overgiet de couscous met kokend water en laat 5 minuten staan.|Meng met tomaatjes en citroen en serveer."),
    R("stoofvlees", "Stoofvlees met aardappelpuree", "diner", 25, 450, "slowcooker fornuis", "rund",
      "stoofvlees:130 ui:60 wortel:80 tomatenpuree:15 bouillon:1 aardappel:250 melk:30",
      7, 34, 600,
      "Doe vlees, ui, wortel, puree en bouillon in de slowcooker en laat 8 uur op laag.|Kook aardappelen gaar en stamp met melk tot puree.|Serveer het vlees met puree."),
    R("slowkipcurry", "Slowcooker kip in kokoscurry", "diner", 20, 360, "slowcooker fornuis", "kip",
      "kippendij:150 kokosmelk:100 ui:60 bloemkool:150 rijst:70 kerrie:1",
      5, 33, 690,
      "Doe alles behalve de rijst in de slowcooker en laat 6 uur op laag.|Kook de rijst.|Roer de curry door en serveer."),
    R("snert", "Snert met rookworst", "diner", 15, 45, "snelkookpan|slowcooker", "varken",
      "spliterwten:70 rookworst:60 prei:60 wortel:60 aardappel:100 bouillon:1",
      15, 24, 470,
      "Doe erwten, groente en bouillon in de snelkookpan.|Kook 30 minuten onder druk, voeg rookworst de laatste 10 minuten toe.|Roer door voor een dikke soep."),
    R("aardappelbonen", "Aardappel met bonen en kaas", "lunch diner", 20, 0, "magnetron oven airfryer", "vega",
      "aardappel:300 kidneybonen:100 kaas:30 yoghurt:40 mais:40",
      12, 21, 470,
      "Prik de aardappel in en gaar 8 minuten in de magnetron of langer in de oven.|Verwarm bonen en mais.|Snijd open en vul met bonen, kaas en yoghurt."),
    R("pompoensoep", "Pompoensoep met kikkererwten", "lunch diner", 35, 0, "fornuis blender|staafmixer", "vega",
      "pompoen:300 ui:60 kokosmelk:50 kikkererwten:80 stokbrood:50 bouillon:1",
      11, 14, 480,
      "Fruit ui, voeg pompoenblokjes en bouillon toe en kook 20 minuten.|Pureer met kokosmelk tot een gladde soep.|Verwarm de kikkererwten en serveer erop met brood."),
    R("tomatensoep", "Tomatensoep met mozzarella", "lunch diner", 30, 0, "fornuis blender|staafmixer", "vega",
      "tomatenblokjes:250 ui:60 wortel:50 kookroom:40 stokbrood:60 mozzarella:40 bouillon:1",
      8, 18, 430,
      "Fruit ui en wortel, voeg tomaat en bouillon toe en kook 15 minuten.|Pureer en roer de kookroom erdoor.|Serveer met stokbrood en mozzarella."),
    R("omelet", "Omelet met champignons en spinazie", "ontbijt lunch diner", 20, 0, "fornuis", "ei",
      "ei:3 champignon:125 spinazie:100 kaas:20 stokbrood:60",
      8, 33, 520,
      "Bak champignons en spinazie kort in een pan.|Giet de losgeklopte eieren erover en laat stollen.|Bestrooi met kaas en serveer met brood."),
    R("garnalenroerbak", "Garnalen roerbak met rijst", "diner", 25, 0, "fornuis", "vis",
      "garnalen:120 roerbakmix:200 rijst:70 sojasaus:15 knoflook:1 ui:40",
      6, 30, 480,
      "Kook de rijst en ontdooi de garnalen.|Roerbak ui, knoflook en groente, voeg de garnalen toe.|Maak af met sojasaus."),
    R("tonijnpasta", "Tonijnpasta met tomatensaus", "lunch diner", 25, 0, "fornuis", "vis",
      "volkorenpasta:90 tonijn:145 tomatenblokjes:200 ui:40 knoflook:1 italiaans:1",
      11, 40, 640,
      "Fruit ui en knoflook, voeg tomaat en kruiden toe en laat 10 minuten koken.|Roer de tonijn erdoor.|Kook de pasta en meng alles."),
    R("hutspot", "Hutspot met gehaktbal", "diner", 45, 0, "fornuis", "rund",
      "aardappel:250 wortel:150 ui:80 gehakt:120 ei:0.5 melk:30",
      9, 32, 650,
      "Kook aardappel, wortel en ui gaar en stamp met melk.|Meng gehakt met ei en bak er gehaktballen van.|Serveer samen."),
    R("dahl", "Dahl met bloemkool en rijst", "diner", 35, 0, "fornuis", "vega",
      "rodelinzen:80 kokosmelk:80 bloemkool:150 ui:60 knoflook:1 rijst:60 kerrie:1",
      12, 26, 700,
      "Fruit ui en knoflook met kerrie.|Voeg linzen, bloemkool, kokosmelk en water toe en kook 20 minuten.|Serveer met rijst."),
    R("kipwraps", "Wraps met kip en yoghurt-dressing", "diner", 25, 0, "fornuis", "kip",
      "kippendij:120 wraps:2 slamix:50 komkommer:0.3 tomaat:80 yoghurt:50 paprikapoeder:1",
      6, 40, 620,
      "Bak de kip met paprikapoeder en snijd in reepjes.|Meng yoghurt met een snufje zout en snijd de groente.|Vul de wraps en rol dicht."),
    R("ovenkip", "Kippendij uit de oven met groente", "diner", 15, 30, "oven", "kip",
      "kippendij:150 aardappel:250 wortel:100 courgette:80 olijfolie:10 paprikapoeder:1",
      9, 36, 600,
      "Snijd groente en aardappel in stukken en meng met olie en paprikapoeder.|Leg de kip erbij op een bakplaat.|Rooster 35 minuten op 200 graden."),
    R("pastaspinazie", "Pasta met spinazie en feta", "diner", 25, 0, "fornuis", "vega",
      "pasta:90 spinazie:150 feta:50 kookroom:40 ui:40 knoflook:1",
      6, 24, 640,
      "Kook de pasta.|Fruit ui en knoflook, voeg spinazie en kookroom toe.|Meng met pasta en verkruimel de feta erover."),
    # ---------------- ONTBIJT ----------------
    R("havermoutpap", "Havermoutpap met banaan en walnoten", "ontbijt", 10, 0, "fornuis|magnetron", "zoet",
      "havermout:50 haverdrink:200 banaan:1 walnoten:15",
      8, 12, 420,
      "Kook havermout en haverdrink 5 minuten tot een pap.|Snijd de banaan in plakjes.|Top met banaan en gehakte walnoten."),
    R("overnightoats", "Overnight oats met blauwe bessen", "ontbijt", 5, 480, "", "zoet",
      "havermout:50 yoghurt:100 haverdrink:100 blauwebessen:60",
      7, 15, 380,
      "Meng havermout, yoghurt en haverdrink in een pot.|Laat een nacht in de koelkast staan.|Top met blauwe bessen."),
    R("yoghurtappel", "Griekse yoghurt met appel en walnoten", "ontbijt", 5, 0, "", "zoet",
      "yoghurt:200 appel:1 walnoten:20 honing:10",
      4, 20, 380,
      "Doe de yoghurt in een kom.|Snijd de appel in blokjes.|Top met appel, walnoten en honing."),
    R("roerei", "Roerei op volkorenbrood met tomaat", "ontbijt", 10, 0, "fornuis", "ei",
      "ei:2 volkorenbrood:2 tomaat:80",
      6, 20, 380,
      "Klop de eieren los en roerbak zacht.|Rooster het brood.|Serveer met plakjes tomaat."),
    R("avotoast", "Avocadotoast met ei", "ontbijt", 10, 0, "fornuis", "ei",
      "volkorenbrood:2 avocado:0.5 ei:1 cherrytomaat:40",
      9, 14, 420,
      "Bak of kook het ei en rooster het brood.|Prak de avocado en smeer op het brood.|Leg het ei en de tomaatjes erop."),
    R("pindabanaan", "Pindakaas-banaan op volkorenbrood", "ontbijt", 5, 0, "", "zoet",
      "volkorenbrood:2 pindakaas:20 banaan:1",
      7, 13, 440,
      "Smeer pindakaas op het brood.|Snijd de banaan in plakjes.|Beleg het brood."),
    R("kwarkhaver", "Kwark met havermout en banaan", "ontbijt", 5, 0, "", "zoet",
      "kwark:200 havermout:30 banaan:1 honing:10",
      5, 26, 360,
      "Doe kwark in een kom.|Voeg havermout en gesneden banaan toe.|Maak af met honing."),
    R("omeletfeta", "Omelet met spinazie en feta", "ontbijt", 15, 0, "fornuis", "ei",
      "ei:3 spinazie:80 feta:30 volkorenbrood:1",
      6, 31, 440,
      "Bak de spinazie kort.|Giet de eieren erover, laat stollen en strooi feta erover.|Serveer met een boterham."),
    R("cottagebrood", "Cottage cheese met komkommer en tomaat op brood", "ontbijt", 5, 0, "", "zuivel",
      "cottage:150 volkorenbrood:2 komkommer:0.3 tomaat:60",
      6, 25, 360,
      "Rooster het brood.|Smeer de cottage cheese erop.|Beleg met komkommer en tomaat."),
    R("smoothie", "Smoothie met banaan en blauwe bessen", "ontbijt", 5, 0, "blender|staafmixer", "zoet",
      "banaan:1 blauwebessen:60 yoghurt:150 haverdrink:150 havermout:30",
      5, 14, 330,
      "Doe alle ingredienten in de blender.|Mix tot een gladde smoothie."),
    R("zalmei", "Gebakken ei met gerookte zalm op brood", "ontbijt", 10, 0, "fornuis", "vis",
      "ei:2 gerooktezalm:50 volkorenbrood:2",
      6, 33, 450,
      "Bak de eieren.|Rooster het brood en leg de zalm erop.|Leg het ei erbij."),
    # ---------------- LUNCH ----------------
    R("tosti", "Tosti met kaas en tomaat", "lunch", 10, 0, "fornuis|oven|magnetron", "zuivel",
      "volkorenbrood:3 kaas:40 tomaat:60",
      7, 18, 430,
      "Beleg het brood met kaas en tomaat.|Bak in een koekenpan tot de kaas smelt."),
    R("hummuswrap", "Wrap met hummus en groente", "lunch", 10, 0, "", "vega",
      "wraps:2 hummus:60 komkommer:0.3 paprika:0.3 slamix:40",
      8, 14, 440,
      "Smeer hummus op de wraps.|Snijd de groente in reepjes.|Beleg en rol op."),
    R("tonijnsalade", "Tonijnsalade met volkorenbrood", "lunch", 10, 0, "", "vis",
      "tonijn:145 volkorenbrood:2 komkommer:0.3 tomaat:80 yoghurt:30",
      6, 33, 400,
      "Meng tonijn met yoghurt.|Snijd komkommer en tomaat.|Serveer op of naast het brood."),
    R("linzensalade", "Linzensalade met feta", "lunch", 10, 0, "", "vega",
      "linzen:150 feta:40 komkommer:0.5 tomaat:100 slamix:40 olijfolie:10",
      12, 22, 420,
      "Spoel de linzen af.|Snijd de groente en meng alles in een kom.|Verkruimel de feta erover."),
    R("groentesoep", "Groentesoep met brood", "lunch", 30, 0, "fornuis", "vega",
      "wortel:120 prei:80 aardappel:100 bouillon:1 volkorenbrood:2",
      9, 9, 330,
      "Snijd de groente en kook 20 minuten in bouillon.|Pureer grof of laat in stukken.|Serveer met brood."),
    R("kipcouscous", "Kipsalade met couscous", "lunch", 20, 0, "fornuis", "kip",
      "kipfilet:100 couscous:50 komkommer:0.3 cherrytomaat:60 slamix:50 citroen:0.25",
      5, 36, 480,
      "Bak de kip gaar en snijd in stukjes.|Overgiet de couscous met kokend water.|Meng met groente en citroensap."),
    R("eiersalade", "Eiersalade op volkorenbrood", "lunch", 15, 0, "fornuis", "ei",
      "ei:3 yoghurt:30 volkorenbrood:2 komkommer:0.3",
      6, 27, 420,
      "Kook de eieren 9 minuten, pel en prak ze.|Meng met yoghurt.|Beleg het brood met salade en komkommer."),
    R("kikkererwtensalade", "Kikkererwtensalade met feta", "lunch", 10, 0, "", "vega",
      "kikkererwten:150 feta:40 komkommer:0.5 cherrytomaat:80 slamix:40 citroen:0.25",
      10, 20, 400,
      "Spoel de kikkererwten af.|Snijd de groente en meng alles.|Besprenkel met citroensap en strooi feta erover."),
    R("couscoussalade", "Couscoussalade met kikkererwten", "lunch", 15, 0, "fornuis|magnetron", "vega",
      "couscous:60 kikkererwten:100 paprika:0.3 komkommer:0.3 citroen:0.25 olijfolie:10",
      9, 17, 470,
      "Overgiet de couscous met kokend water.|Meng met kikkererwten en gesneden groente.|Maak af met citroen en olie."),

    # ---------------- UITBREIDING ----------------
    R("kipketjap", "Kip in ketjap met rijst", "diner", 25, 0, "fornuis", "kip",
      "kippendij:130 ketjap:20 rijst:70 roerbakmix:150 knoflook:1 ui:40", 0, 0, 0,
      "Kook de rijst.|Bak de kip bruin met ui en knoflook.|Voeg groente en ketjap toe en laat 5 minuten sudderen."),
    R("ovenkipbroccoli", "Ovenschotel kip met broccoli en aardappel", "diner", 15, 35, "oven", "kip",
      "kipfilet:120 aardappel:250 broccoli:150 kookroom:40 kaas:30", 0, 0, 0,
      "Kook de aardappel half gaar en snijd in plakken.|Meng met kip in blokjes, broccoli en kookroom in een schaal.|Bestrooi met kaas en bak 30 minuten op 200 graden."),
    R("bloemkoolcurry", "Bloemkoolcurry met kikkererwten", "diner", 30, 0, "fornuis", "vega",
      "bloemkool:200 kikkererwten:100 kokosmelk:100 tomatenblokjes:100 ui:60 kerrie:1 rijst:60", 0, 0, 0,
      "Kook de rijst.|Fruit ui met kerrie, voeg bloemkool, kikkererwten, tomaat en kokosmelk toe.|Laat 15 minuten zacht koken."),
    R("linzendahl", "Rode linzendahl met spinazie en rijst", "diner", 30, 0, "fornuis", "vega",
      "rodelinzen:60 spinazie:100 ui:60 knoflook:1 kokosmelk:60 kerrie:1 rijst:60 tomatenblokjes:100", 0, 0, 0,
      "Kook de rijst.|Fruit ui en knoflook met kerrie, voeg linzen, tomaat en 200 ml water toe.|Laat 15 minuten koken, roer kokosmelk en spinazie erdoor."),
    R("gehaktrijst", "Gehaktschotel met paprika en rijst", "diner", 30, 0, "fornuis", "rund",
      "gehakt:110 paprika:0.5 mais:50 tomatenblokjes:150 rijst:70 komijn:1 ui:50", 0, 0, 0,
      "Kook de rijst.|Bak gehakt rul met ui en komijn, voeg paprika, mais en tomaat toe.|Laat 10 minuten pruttelen en serveer op de rijst."),
    R("zalmpasta", "Zalmpasta met spinazie", "diner", 25, 0, "fornuis", "vis",
      "zalm:100 pasta:90 spinazie:80 kookroom:50 citroen:0.25", 0, 0, 0,
      "Kook de pasta.|Bak de zalm in stukjes en voeg spinazie en kookroom toe.|Meng met pasta en citroensap."),
    R("caprese", "Pasta caprese met mozzarella", "diner", 20, 0, "fornuis", "vega",
      "pasta:90 mozzarella:60 cherrytomaat:120 pesto:20 slamix:20", 0, 0, 0,
      "Kook de pasta.|Verwarm de tomaatjes kort met de pesto.|Meng met pasta en mozzarella en serveer met sla."),
    R("gevuldepaprika", "Gevulde paprika met gehakt", "diner", 20, 30, "oven", "rund",
      "paprika:1 gehakt:100 rijst:40 tomatenblokjes:100 ui:40 kaas:25", 0, 0, 0,
      "Kook de rijst en bak het gehakt met ui en tomaat.|Meng en vul de paprikahelften.|Bestrooi met kaas en bak 30 minuten op 200 graden."),
    R("linzenstoof", "Rode linzenstoofpot met zoete aardappel", "diner", 35, 0, "fornuis", "vega",
      "rodelinzen:60 zoeteaardappel:200 tomatenblokjes:150 ui:60 knoflook:1 komijn:1 spinazie:60", 0, 0, 0,
      "Fruit ui en knoflook met komijn.|Voeg linzen, zoete aardappelblokjes, tomaat en water toe en laat 25 minuten koken.|Roer de spinazie erdoor."),
    R("traybake", "Traybake kip met aardappel en wortel", "diner", 15, 35, "oven", "kip",
      "kippendij:150 aardappel:200 wortel:100 paprikapoeder:1 olijfolie:10 yoghurt:40", 0, 0, 0,
      "Snijd aardappel en wortel in stukken en meng met olie en paprikapoeder.|Leg de kip erbij en bak 35 minuten op 200 graden.|Serveer met yoghurt."),
    R("gebakkenrijst", "Gebakken rijst met ei en groente", "diner", 20, 0, "fornuis", "ei",
      "rijst:70 ei:2 roerbakmix:150 sojasaus:15 knoflook:1 ui:30", 0, 0, 0,
      "Kook de rijst en laat afkoelen.|Roerbak ui, knoflook en groente.|Voeg rijst en sojasaus toe, schuif opzij en bak de eieren erdoor."),
    R("slowkipbonen", "Slowcooker kip met bonen en paprika", "diner", 15, 360, "slowcooker", "kip",
      "kipfilet:120 kidneybonen:80 tomatenblokjes:150 paprika:0.5 ui:50 komijn:1 paprikapoeder:1", 0, 0, 0,
      "Doe alles in de slowcooker.|Laat 6 uur op laag staan.|Rafel de kip en roer door."),
    R("miepinda", "Mie met tofu en pindasaus", "diner", 25, 0, "fornuis", "vega",
      "mie:70 tofu:150 pindakaas:25 ketjap:15 roerbakmix:150", 0, 0, 0,
      "Kook de mie.|Bak de tofu krokant en roerbak de groente.|Roer pindakaas, ketjap en een scheutje water tot saus en meng alles."),
    R("havermoutbanaan", "Havermout met banaan en walnoten", "ontbijt", 10, 0, "fornuis|magnetron", "vega",
      "havermout:50 melk:150 banaan:1 walnoten:15 honing:10", 0, 0, 0,
      "Verwarm havermout met melk tot een pap.|Snijd de banaan.|Top met banaan, walnoten en honing."),
    R("yoghurtbessen", "Griekse yoghurt met blauwe bessen en noten", "ontbijt", 5, 0, "", "vega",
      "yoghurt:150 blauwebessen:60 walnoten:15 honing:10 havermout:20", 0, 0, 0,
      "Schep de yoghurt in een kom.|Top met bessen, walnoten en havermout.|Maak af met honing."),
    R("kwarkbanaan", "Kwark met banaan en havermout", "ontbijt", 5, 0, "", "vega",
      "kwark:150 banaan:1 havermout:30 honing:5", 0, 0, 0,
      "Schep de kwark in een kom.|Snijd de banaan erover.|Strooi havermout en honing erbij."),
    R("capresebrood", "Broodje tomaat mozzarella", "lunch", 10, 0, "", "vega",
      "stokbrood:80 mozzarella:60 tomaat:100 pesto:10", 0, 0, 0,
      "Snijd het stokbrood open en smeer pesto erop.|Beleg met tomaat en mozzarella.|Sluit en serveer."),
    R("zalmbrood", "Gerookte zalm op brood met kwark", "lunch", 5, 0, "", "vis",
      "gerooktezalm:50 volkorenbrood:2 kwark:40 komkommer:0.3 citroen:0.1", 0, 0, 0,
      "Smeer kwark op het brood.|Leg zalm en komkommer erop.|Knijp wat citroen erover."),
]

NUTR = {
    "ui":(40,1.1,1.7),"knoflook":(140,6.4,2.1),"tomaat":(18,.9,1.2),"cherrytomaat":(20,.9,1.2),"paprika":(30,1,2),"courgette":(17,1.2,1),
    "wortel":(36,.6,3),"champignon":(22,3,1),"broccoli":(34,2.8,2.6),"bloemkool":(25,2,2.5),"sperzieboon":(31,1.8,3),"aardappel":(77,2,1.8),
    "zoeteaardappel":(86,1.6,3),"komkommer":(12,.6,.6),"slamix":(15,1.3,1.5),"prei":(31,1.8,2.3),"pompoen":(45,1,1.5),"citroen":(29,1.1,2.8),
    "roerbakmix":(30,2,2.5),"boerenkool":(49,4,4),"banaan":(90,1.1,2.6),"appel":(52,.3,2.4),"blauwebessen":(57,.7,2.4),"avocado":(160,2,6.7),
    "kipfilet":(110,23,0),"kippendij":(125,19,0),"gehakt":(190,20,0),"rookworst":(250,13,0),"stoofvlees":(130,22,0),"zalm":(200,20,0),
    "gerooktezalm":(180,22,0),"ei":(143,12.5,0),"melk":(46,3.4,0),"haverdrink":(45,.5,.8),"kookroom":(200,2.5,0),"kaas":(350,25,0),
    "feta":(260,15,0),"mozzarella":(250,18,0),"yoghurt":(120,5,0),"kwark":(57,10,0),"cottage":(98,11,0),"tofu":(120,13,1.5),
    "wraps":(300,8,2.5),"stokbrood":(270,9,3),"volkorenbrood":(240,9,6.5),"pasta":(360,12,3),"volkorenpasta":(350,13,8),"rijst":(355,7,1),
    "zilvervliesrijst":(350,8,3),"mie":(360,12,3),"couscous":(355,12,3.5),"rodelinzen":(340,24,11),"spliterwten":(340,23,15),
    "havermout":(370,13,10),"walnoten":(650,15,6.7),"tomatenblokjes":(20,1,1.2),"tomatenpuree":(80,4,4),"kidneybonen":(100,7,6),
    "kikkererwten":(120,8,6),"linzen":(105,8,6),"mais":(80,3,3),"kokosmelk":(170,1.5,0),"tonijn":(110,25,0),"pindakaas":(600,25,6),
    "ketjap":(130,2,0),"sojasaus":(70,8,0),"pesto":(450,5,2),"hummus":(250,7,5),"honing":(330,.3,0),"spinazie":(25,3,2.5),"garnalen":(85,18,0),
    "olijfolie":(820,0,0),"kerrie":(325,14,53),"komijn":(375,18,11),"paprikapoeder":(280,14,35),"italiaans":(270,10,30),"bouillon":(10,.5,0),"mosterd":(100,6,3),
}
GRAM = {"knoflook":4,"paprika":150,"komkommer":300,"citroen":60,"banaan":120,"appel":150,"avocado":150,"ei":55,"wraps":60,"volkorenbrood":35,"bouillon":10}


def nutrition(r):
    kc = pr = fi = 0.0
    for iid, a in r["ing"]:
        g = a * GRAM.get(iid, 1)
        k, p, f = NUTR[iid]
        kc += g * k / 100; pr += g * p / 100; fi += g * f / 100
    return round(fi), round(pr), round(kc / 10) * 10


for r in REC:
    v, e, kc = nutrition(r)
    if r["kcal"] and (abs(e - r["e"]) > 6 or abs(v - r["v"]) > 4 or abs(kc - r["kcal"]) > 150):
        print("AFWIJKING", r["id"], "oud v/e/kcal", r["v"], r["e"], r["kcal"], "nieuw", v, e, kc)
    r["v"], r["e"], r["kcal"] = v, e, kc


# validatie
ids = {i["id"] for i in ING}
assert len(ids) == len(ING), "dubbele ingredient ids"
rids = set()
for r in REC:
    assert r["id"] not in rids, r["id"]
    rids.add(r["id"])
    for ing_id, _ in r["ing"]:
        assert ing_id in ids, (r["id"], ing_id)

data = dict(stores=STORES, appliances=APPLIANCES, allergens=ALLERGENS, depts=DEPTS, ingredients=ING, recipes=REC)
with open("data.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
print(len(ING), "ingredienten,", len(REC), "recepten")
