"""Streng matchen: een product telt alleen als ALLE woorden in de naam (na weghalen van merk,
cijfers en vulwoorden) bij het ingredient horen. Liever 'niet gevonden' (dan schat de app)
dan een verkeerd product zoals babyhapjes of een kant-en-klaarmaaltijd.

K[id] = (kernwoorden waarvan er minstens een voorkomt, extra toegestane woorden)"""
GEN = ("gele rode witte groene vastkokende kruimige kruimig vastkokend nieuwe hollandse nederlandse verse vers grove grof "
       "naturel original origineel traditioneel trad klassiek halfvolle halfvol magere mager extra jong jonge belegen oude oud "
       "scharrel scharrelei vrije uitloop biologisch bio plus premium finest terra la grand italia italiaanse tros trostomaten "
       "gewassen geschild los voordeel grootverpakking kleinverpakking schaal doos bak net zak pak pakje pot blik "
       "plantaardige plantaardig ongezoet ongezouten zonder suiker gezouten fairtrade ready eat rijp later lekker "
       "maat m l xl s medium large small van goede afkomst per stuk stuks pack st").split()
K = {
 "ui": ("ui uien", "gele rode"),
 "tomaat": ("tomaten tomaat trostomaten", "tros vleestomaten"),
 "cherrytomaat": ("cherry cherrytomaten", "tomaten tomaat tros cherrytomaat"),
 "paprika": ("paprika paprikas puntpaprika", "punt palermo sweet"),
 "courgette": ("courgette courgettes", ""),
 "wortel": ("wortel wortelen waspeen winterpeen peen", "winter"),
 "champignon": ("champignons champignon kastanjechampignons", "kastanje wit"),
 "broccoli": ("broccoli", ""),
 "bloemkool": ("bloemkool", ""),
 "sperzieboon": ("sperziebonen sperzieboon", "franse gebroken"),
 "aardappel": ("aardappelen aardappel", "kruimige vastkokende"),
 "zoeteaardappel": ("aardappel aardappelen", "zoete oranje zoet"),
 "komkommer": ("komkommer komkommers", "midi veld"),
 "slamix": ("salade sla", "mix gemengde fris krokante lunch"),
 "prei": ("prei", "grof"),
 "pompoen": ("pompoen butternut", "muskaat"),
 "citroen": ("citroen citroenen", ""),
 "roerbakmix": ("roerbakgroente roerbakgroenten wokgroenten wokgroente", "oosterse oosters mix italiaanse"),
 "boerenkool": ("boerenkool", "gesneden hak"),
 "banaan": ("bananen banaan", "dole chiquita"),
 "appel": ("appels appel elstar jonagold kanzi braeburn", "schaal friszoet sappig"),
 "blauwebessen": ("blauwe bessen", "bessen diepvries"),
 "avocado": ("avocado avocados", "eetrijp ready"),
 "kipfilet": ("kipfilet kipfilets", "stuks scharrel"),
 "kippendij": ("kippendij kippendijen kippendijfilet kippendijfilets", "filet scharrelkip"),
 "gehakt": ("rundergehakt gehakt", "rund runder mager 15 20 minder vet"),
 "rookworst": ("rookworst", "gelderse hollandse magere extra"),
 "stoofvlees": ("stoofvlees riblappen stooflappen riblap", ""),
 "zalm": ("zalmfilet zalmfilets zalm", "huid met op"),
 "gerooktezalm": ("zalm", "gerookte gerookt warm warmgerookte"),
 "ei": ("eieren scharreleieren", "verse"),
 "melk": ("melk", "halfvolle halfvol"),
 "haverdrink": ("haverdrink havermelk", ""),
 "kookroom": ("kookroom", "20 vet 15 7"),
 "kaas": ("kaas", "geraspte raspkaas rasp geraspt jong belegen"),
 "feta": ("feta", "griekse"),
 "mozzarella": ("mozzarella", ""),
 "yoghurt": ("yoghurt", "griekse stijl grieks"),
 "kwark": ("kwark", "magere mager"),
 "cottage": ("cottage", "cheese"),
 "tofu": ("tofu", "stevige zachte"),
 "wraps": ("wraps tortilla tortillas", "naturel large wrap"),
 "stokbrood": ("stokbrood baguette", "volkoren wit"),
 "volkorenbrood": ("volkorenbrood brood", "volkoren heel half heel"),
 "pasta": ("penne spaghetti fusilli farfalle rigatoni macaroni", "pasta tagliatelle"),
 "volkorenpasta": ("penne spaghetti fusilli farfalle rigatoni macaroni", "volkoren pasta"),
 "rijst": ("rijst basmati", "pure langkorrel jasmijn"),
 "zilvervliesrijst": ("zilvervliesrijst", "rijst"),
 "mie": ("mie noedels", "nestjes eiernoedels"),
 "couscous": ("couscous", "durum volkoren"),
 "rodelinzen": ("linzen", "rode"),
 "spliterwten": ("spliterwten", "gedroogde groene"),
 "havermout": ("havermout", "vlokken grove fijne"),
 "walnoten": ("walnoten", "ongebrand"),
 "tomatenblokjes": ("tomatenblokjes", ""),
 "tomatenpuree": ("tomatenpuree", "dubbel geconcentreerd"),
 "kidneybonen": ("kidneybonen kidney", "bonen boon pak zak"),
 "kikkererwten": ("kikkererwten", "pak zak"),
 "linzen": ("linzen", "bruine groene"),
 "mais": ("mais maïs", "zoete"),
 "kokosmelk": ("kokosmelk", "light"),
 "tonijn": ("tonijn tonijnstukken tonijnmoot tonijnstukjes", "in water stukken moot stukjes"),
 "pindakaas": ("pindakaas", "naturel pot"),
 "ketjap": ("ketjap", "manis"),
 "sojasaus": ("sojasaus", ""),
 "pesto": ("pesto", "groene verde genovese basilicum romige"),
 "hummus": ("hummus", ""),
 "honing": ("honing", "bloemenhoning vloeibaar"),
 "spinazie": ("spinazie", ""),
 "garnalen": ("garnalen garnaal", "rauw gepeld gekookte"),
}
